apiVersion: v1
kind: Service
metadata:
  name: camerasserver-service
spec:
  selector:
    app: camerasserver
  ports:
    - name: camera1
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 31001  # Escolha um número de porta disponível
    - name: camera2
      protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 31002  # Escolha um número de porta disponível
    - name: camera3
      protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 31003  # Escolha um número de porta disponível
    - name: camera4
      protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 31004  # Escolha um número de porta disponível
  type: NodePort
